### ISSUE TITLE
Please add a README with screenshots

### ISSUE THREAD

**Issue by MarkJr94** [saresend/shack#1]
This project sounds really cool and like something I might use, but I can't be sure without more information, and hopefully it can be present for others without reading the source

**Comment by saresend** [comment]
Hey! Sorry, I wasn't able to respond earlier, I've been working on this intermittently since I'm currently in university. I'm currently finishing up the last kinks with it, and part of that is definitely adding a more comprehensive README with screenshots, installation, etc. My plan is to have all of this up and ready to go by the end of this week! 😃

**Comment by saresend** [comment]
Quick Update: Just added some stuff to the README. Let me know if its sufficient and if theres anything else worth adding! Cheers 😀
